function varargout = unitslist(varargin)
%UNITSLIST List of supported units for Simulink.Parameter objects and
%Simulink.Signal objects

import('ptc_matlab_lib.*');
pairs = {'Interpreter', 'none'};
parseargs(varargin, pairs);

%Format: {RawString1, TeXString1;
%         RawString2, TeXString2;
%         RawString3, TeXString3 ...}
cellarray = {'<empty>'                                        '<empty>'
    'Acceleration : m s^-2'                          'Acceleration : m s^{-2}'
    'Activity : Bq'                                  'Activity : Bq'
    'Amount Of Substance : mol'                      'Amount Of Substance : mol'
    'Angular Acceleration : rad s^-2'                'Angular Acceleration : rad s^{-2}'
    'Angular Momentum : kg m^2 s^-1'                 'Angular Momentum : kg m^2 s^{-1}'
    'Angular Velocity : rad s^-1'                    'Angular Velocity : rad s^{-1}'
    'Angular Velocity : rpm'                         'Angular Velocity : rpm'
    'Angular Velocity : rps'                         'Angular Velocity : rps'
    'Area : m^2'                                     'Area : m^2'
    'Area Density : kg m^-2'                         'Area Density : kg m^{-2}'
    'Baud Rate : Bd'                                 'Baud Rate : Bd'
    'Baud Rate : kBd'                                'Baud Rate : kBd'
    'Capacitance : F'                                'Capacitance : F'
    'Capacitance : pF'                               'Capacitance : pF'
    'Capacitance : uF'                               'Capacitance : {\mu}F'
    'Catalytic Activity : kat'                       'Catalytic Activity : kat'
    'Catalytic Activity Concentration : kat m^-3'    'Catalytic Activity Concentration : kat m^{-3}'
    'Chemical Potential : J mol^-1'                  'Chemical Potential : J mol^{-1}'
    'Current Density : A m^-2'                       'Current Density : A m^{-2}'
    'Custom : % rpm^-1'                              'Custom : % rpm^(-1)'
    'Digital Information : B'                        'Digital Information : B'
    'Digital Information : GB'                       'Digital Information : GB'
    'Digital Information : Gbit'                     'Digital Information : Gbit'
    'Digital Information : GiB'                      'Digital Information : GiB'
    'Digital Information : Gibit'                    'Digital Information : Gibit'
    'Digital Information : KiB'                      'Digital Information : KiB'
    'Digital Information : Kibit'                    'Digital Information : Kibit'
    'Digital Information : MB'                       'Digital Information : MB'
    'Digital Information : Mbit'                     'Digital Information : Mbit'
    'Digital Information : MiB'                      'Digital Information : MiB'
    'Digital Information : Mibit'                    'Digital Information : Mibit'
    'Digital Information : PB'                       'Digital Information : PB'
    'Digital Information : PiB'                      'Digital Information : PiB'
    'Digital Information : TB'                       'Digital Information : TB'
    'Digital Information : TiB'                      'Digital Information : TiB'
    'Digital Information : Tibit'                    'Digital Information : Tibit'
    'Digital Information : bit'                      'Digital Information : bit'
    'Digital Information : kB'                       'Digital Information : kB'
    'Digital Information : kbit'                     'Digital Information : kbit'
    'Digital Information : nibble'                   'Digital Information : nibble'
    'Dose : Gy'                                      'Dose : Gy'
    'Dose : rad'                                     'Dose : rad'
    'Dose Equivalent : Sv'                           'Dose Equivalent : Sv'
    'Dose Equivalent : rem'                          'Dose Equivalent : rem'
    'Dose Rate : Gy s^-1'                            'Dose Rate : Gy s^{-1}'
    'Dynamic Viscosity : Pa s'                       'Dynamic Viscosity : Pa s'
    'Electric Charge : C'                            'Electric Charge : C'
    'Electric Charge Density : C m^-3'               'Electric Charge Density : C m^{-3}'
    'Electric Current : A'                           'Electric Current : A'
    'Electric Current : mA'                          'Electric Current : mA'
    'Electric Current : uA'                          'Electric Current : {\mu}A'
    'Electric Displacement : C m^-2'                 'Electric Displacement : C m^{-2}'
    'Electric Field Strength : V m^-1'               'Electric Field Strength : V m^{-1}'
    'Electric Potential : V'                         'Electric Potential : V'
    'Electric Potential : mV'                        'Electric Potential : mV'
    'Electric Potential : uV'                        'Electric Potential : {\mu}V'
    'Electrical Conductance : S'                     'Electrical Conductance : S'
    'Electrical Conductivity : S m^-1'               'Electrical Conductivity : S m^{-1}'
    'Electrical Energy : MWh'                        'Electrical Energy : MWh'
    'Electrical Energy : Wh'                         'Electrical Energy : Wh'
    'Electrical Energy : kWh'                        'Electrical Energy : kWh'
    'Electrical Energy : mWh'                        'Electrical Energy : mWh'
    'Electrical Resistance : ohm'                    'Electrical Resistance : ohm'
    'Electrical Resistivity : ohm m'                 'Electrical Resistivity : ohm m'
    'Energy : Btu'                                   'Energy : Btu'
    'Energy : J'                                     'Energy : J'
    'Energy : cal'                                   'Energy : cal'
    'Energy : erg'                                   'Energy : erg'
    'Energy : ft lb'                                 'Energy : ft lb'
    'Energy : ft lbf'                                'Energy : ft lbf'
    'Energy : kcal'                                  'Energy : kcal'
    'Energy Density : J m^-3'                        'Energy Density : J m^{-3}'
    'Entropy : J K^-1'                               'Entropy : J K^{-1}'
    'Exposure To Radiation : R'                      'Exposure To Radiation : R'
    'Exposure To Radiation : mR'                     'Exposure To Radiation : mR'
    'Exposure To Radiation : uR'                     'Exposure To Radiation : {\mu}R'
    'FLOPS : FLOPS'                                  'FLOPS : FLOPS'
    'FLOPS : gigaFLOPS'                              'FLOPS : gigaFLOPS'
    'FLOPS : kiloFLOPS'                              'FLOPS : kiloFLOPS'
    'FLOPS : megaFLOPS'                              'FLOPS : megaFLOPS'
    'FLOPS : teraFLOPS'                              'FLOPS : teraFLOPS'
    'Force : N'                                      'Force : N'
    'Force : gf'                                     'Force : gf'
    'Force : kgf'                                    'Force : kgf'
    'Frequency : Hz'                                 'Frequency : Hz'
    'Fuel Economy : km L^-1'                         'Fuel Economy : km L^{-1}'
    'Fuel Economy : mpg (Imperial)'                  'Fuel Economy : mpg (Imperial)'
    'Fuel Economy : mpg (US)'                        'Fuel Economy : mpg (US)'
    'Half-life : s'                                  'Half-life : s'
    'Heat : J'                                       'Heat : J'
    'Heat : cal'                                     'Heat : cal'
    'Heat : erg'                                     'Heat : erg'
    'Heat : kcal'                                    'Heat : kcal'
    'Heat Capacity : J K^-1'                         'Heat Capacity : J K^{-1}'
    'Heat Flux Density : W m^-2'                     'Heat Flux Density : W m^{-2}'
    'Illuminance : lx'                               'Illuminance : lx'
    'Impedance : ohm'                                'Impedance : ohm'
    'Impulse : kg m s^-1'                            'Impulse : kg m s^{-1}'
    'Index Of Refraction : <empty>'                  'Index Of Refraction : <empty>'
    'Inductance : H'                                 'Inductance : H'
    'Intensity : dB'                                 'Intensity : dB'
    'Irradiance : W m^-2'                            'Irradiance : W m^{-2}'
    'Length : cm'                                    'Length : cm'
    'Length : inch'                                  'Length : inch'
    'Length : km'                                    'Length : km'
    'Length : m'                                     'Length : m'
    'Length : mm'                                    'Length : mm'
    'Length : um'                                    'Length : {\mu}m'
    'Linear Density : kg m^-1'                       'Linear Density : kg m^{-1}'
    'Luminous Flux : lm'                             'Luminous Flux : lm'
    'Luminous Intensity : cd'                        'Luminous Intensity : cd'
    'Magnetic Field Strength : A m^-1'               'Magnetic Field Strength : A m^{-1}'
    'Magnetic Flux : Wb'                             'Magnetic Flux : Wb'
    'Magnetic Flux Density : T'                      'Magnetic Flux Density : T'
    'Magnetic Flux Density : Wb m^-2'                'Magnetic Flux Density : Wb m^{-2}'
    'Magnetization : A m^-1'                         'Magnetization : A m^{-1}'    
    'Mass : g'                                       'Mass : g'
    'Mass : kg'                                      'Mass : kg'
    'Mass : mg'                                      'Mass : mg'
    'Mass : t'                                       'Mass : t'
    'Mass Concentration : g L^-1'                    'Mass Concentration : g L^{-1}'    
    'Mass Density : g L^-1'                          'Mass Density : g L^{-1}'
    'Mass Density : kg m^-3'                         'Mass Density : kg m^{-3}'
    'Mass Density : mg m^-3'                         'Mass Density : mg m^{-3}'
    'Mass Flow Rate : g hr^-1'                       'Mass Flow Rate : g hr^{-1}'
    'Mass Flow Rate : g s^-1'                        'Mass Flow Rate : g s^{-1}'
    'Mass Flow Rate : kg s^-1'                       'Mass Flow Rate : kg s^{-1}'
    'Mass Flow Rate : mg s^-1'                       'Mass Flow Rate : mg s^{-1}'
    'Mass Fraction : <empty>'                        'Mass Fraction : <empty>'
    'Mass Fraction : ppm'                            'Mass Fraction : ppm'
    'Mass Fraction : ppq'                            'Mass Fraction : ppq'
    'Mass Fraction : ppt'                            'Mass Fraction : ppt'
    'Mean Lifetime : s'                              'Mean Lifetime : s'
    'Miscellaneous : gear value'                     'Miscellaneous : gear value'    
    'Molar Concentration : mol m^-3'                 'Molar Concentration : mol m^{-3}'
    'Molar Energy : J mol^-1'                        'Molar Energy : J mol^{-1}'
    'Molar Entropy : J K^-1 mol^-1'                  'Molar Entropy : J K^{-1} mol^{-1}'
    'Molar Heat Capacity : J K^-1 mol^-1'            'Molar Heat Capacity : J K^{-1} mol^{-1}'
    'Mole Fraction : ppm'                            'Mole Fraction : ppm'
    'Mole Fraction : ppq'                            'Mole Fraction : ppq'
    'Mole Fraction : ppt'                            'Mole Fraction : ppt'
    'Moment Of Inertia : kg m^2'                     'Moment Of Inertia : kg m^2'
    'Momentum : N s'                                 'Momentum : N s'
    'Optical Power : m^-1'                           'Optical Power : m^-1'
    'Percent : %'                                    'Percent : %'
    'Permeability : H m^-1'                          'Permeability : H m^{-1}'
    'Permittivity : F m^-1'                          'Permittivity : F m^{-1}'
    'Plane Angle : deg'                              'Plane Angle : \circ'
    'Plane Angle : rad'                              'Plane Angle : rad'
    'Power : BHP'                                    'Power : BHP'
    'Power : GW'                                     'Power : GW'
    'Power : HP'                                     'Power : HP'
    'Power : MW'                                     'Power : MW'
    'Power : W'                                      'Power : W'
    'Power : kW'                                     'Power : kW'
    'Power : mW'                                     'Power : mW'
    'Pressure : MPa'                                 'Pressure : MPa'
    'Pressure : Pa'                                  'Pressure : Pa'
    'Pressure : bar'                                 'Pressure : bar'
    'Pressure : kPa'                                 'Pressure : kPa'
    'Pressure : psi'                                 'Pressure : psi'
    'Radiance : W m^-2 s^-1'                         'Radiance : W m^{-2} s^{-1}'
    'Radiant Intensity : W sr^-1'                    'Radiant Intensity : W sr^{-1}'
    'Ratio : %'                                      'Ratio : %'
    'Ratio : <empty>'                                'Ratio : <empty>'
    'Reaction Rate : mol m^-3 s^-1'                  'Reaction Rate : mol m^{-3} s^{-1}'
    'Solid Angle : sr'                               'Solid Angle : sr'
    'Specific Energy : J kg^-1'                      'Specific Energy : J kg^{-1}'
    'Specific Heat Capacity : J kg^-1 K^-1'          'Specific Heat Capacity : J kg^{-1} K^{-1}'
    'Speed : km hr^-1'                               'Speed : km hr^{-1}'
    'Speed : m s^-1'                                 'Speed : m s^{-1}'
    'Speed : mph'                                    'Speed : mph'
    'Spin : kg m^2 s^-1'                             'Spin : kg m^2 s^{-1}'
    'Stress : MPa'                                   'Stress : MPa'
    'Stress : Pa'                                    'Stress : Pa'
    'Stress : kPa'                                   'Stress : kPa'
    'Surface Tension : N m^-1'                       'Surface Tension : N m^{-1}'
    'Temperature : K'                                'Temperature : K'
    'Temperature : deg C'                            'Temperature : \circC'
    'Temperature : deg F'                            'Temperature : \circF'
    'Thermal Conductivity : W m^-1 K^-1'             'Thermal Conductivity : W m^{-1} K^{-1}'
    'Time : day'                                     'Time : day'
    'Time : fs'                                      'Time : fs'
    'Time : hr'                                      'Time : hr'
    'Time : min'                                     'Time : min'
    'Time : ms'                                      'Time : ms'
    'Time : ns'                                      'Time : ns'
    'Time : ps'                                      'Time : ps'
    'Time : s'                                       'Time : s'
    'Time : us'                                      'Time : {\mu}s'
    'Torque : N m'                                   'Torque : N m'
    'Torque : lb ft'                                 'Torque : lb ft'
    'Velocity : km hr^-1'                            'Velocity : km hr^{-1}'
    'Velocity : m s^-1'                              'Velocity : m s^{-1}'
    'Velocity : mph'                                 'Velocity : mph'
    'Viscosity : Pa s'                               'Viscosity : Pa s'
    'Volume : L'                                     'Volume : L'
    'Volume : cc'                                    'Volume : cc'
    'Volume : cm^3'                                  'Volume : cm^3'
    'Volume : fl oz (Imperial)'                      'Volume : fl oz (Imperial)'
    'Volume : fl oz (US)'                            'Volume : fl oz (US)'
    'Volume : mL'                                    'Volume : mL'
    'Volume : m^3'                                   'Volume : m^3'
    'Volume : mm^3'                                  'Volume : mm^3'
    'Volume : uL'                                    'Volume : {\mu}L'
    'Volume Density : kg m^-3'                       'Volume Density : kg m^{-3}'
    'Volumetric Flow Rate : L s^-1'                  'Volumetric Flow Rate : L s^{-1}'
    'Volumetric Flow Rate : L hr^-1'                 'Volumetric Flow Rate : L hr^{-1}'
    'Volumetric Flow Rate : cc s^-1'                 'Volumetric Flow Rate : cc s^{-1}'
    'Volumetric Flow Rate : ft^3 s^-1'               'Volumetric Flow Rate : ft^3 s^{-1}'
    'Volumetric Flow Rate : mL s^-1'                 'Volumetric Flow Rate : mL s^{-1}'
    'Volumetric Flow Rate : m^3 s^-1'                'Volumetric Flow Rate : m^3 s^{-1}'
    'Volumetric Flow Rate : mm^3 s^-1'               'Volumetric Flow Rate : mm^3 s^{-1}'
    'Volumetric Flow Rate : uL s^-1'                 'Volumetric Flow Rate : {\mu}L s^{-1}'
    'Wavelength : m'                                 'Wavelength : m'
    'Wavenumber : m^-1'                              'Wavenumber : m^{-1}'
    'Weight : N'                                     'Weight : N'
    'Weight : gf'                                    'Weight : gf'
    'Weight : kgf'                                   'Weight : kgf'
    'Work : J'                                       'Work : J'
    'Work : erg'                                     'Work : erg'
    'Work : ft lb'                                   'Work : ft lb'
    'Work : ft lbf'                                  'Work : ft lbf'};

switch Interpreter
    case 'none'
        varargout{1} = sort(cellarray(:, 1));
    case 'tex'
        varargout{1} = sort(cellarray(:, 2));
    otherwise
        error([mfilename ':' thisfuncname ':InvalidInterpreter'], 'Invalid interpreter');
end

end