%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% Autogenerated by export_data_dictionary.m
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

%% ABS_VEHICLE_MASS_APV
ABS_VEHICLE_MASS_APV = ptc_matlab_lib.PTC_MBDS_Parameter('Value', 29491, ...
	'Description', 'Vehicle mass', ...
	'Unit', 'kg');
