%% PLANT_ENGINE_REFERENCE_TRQ_APV
PLANT_ENGINE_REFERENCE_TRQ_APV = ptc_matlab_lib.PTC_MBDS_Parameter('Value', max(PLANT_ENGINE_INDICATED_TORQUE_DATA_MPV.Value), ...
'Description', 'Maximum Torque value for the current torque curve equal to 100% actual engine torque', ...
'Unit', 'N*m');

%% PLANT_RETARDER_REFERENCE_TRQ_APV
PLANT_RETARDER_REFERENCE_TRQ_APV = ptc_matlab_lib.PTC_MBDS_Parameter('Value', max(PLANT_RETARDER_TORQUE_DATA_MPV.Value), ...
'Description', 'Maximum Torque value for the current retarder torque curve equal to 100% retarder torque', ...
'Unit', 'N*m');