%% PCI_ENGINE_REFERENCE_TRQ_APV
PCI_ENGINE_REFERENCE_TRQ_APV = ptc_matlab_lib.PTC_MBDS_Parameter('Value', max(PCI_ENGINE_INDICATED_TORQUE_DATA_MPV.Value), ...
    'Description', 'Maximum Torque value for the current torque curve equal to 100% actual engine torque', ...
    'Unit', 'N*m');