%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% Autogenerated by export_data_dictionary.m
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

%% CANR_PROPB_REAX_3_13_CHANNEL_APV
CANR_PROPB_REAX_3_13_CHANNEL_APV = ptc_matlab_lib.PTC_MBDS_Parameter('Value', ENUM_CAN_RX_T.RX_CAN_1, ...
	'Description', 'Channel to receive PropB_REAX_3_13');

%% CANR_PROPB_REAX_4_13_CHANNEL_APV
CANR_PROPB_REAX_4_13_CHANNEL_APV = ptc_matlab_lib.PTC_MBDS_Parameter('Value', ENUM_CAN_RX_T.RX_CAN_1, ...
	'Description', 'Channel to receive PropB_REAX_4_13');

%% CANR_PROPB_XPR_1_50_CHANNEL_APV
CANR_PROPB_XPR_1_50_CHANNEL_APV = ptc_matlab_lib.PTC_MBDS_Parameter('Value', ENUM_CAN_RX_T.RX_CAN_1, ...
	'Description', 'Channel to receive PropB_XPR_1_50');

%% PROPB_REAX_1_E4_DESIRED_OPMODE_APV
PROPB_REAX_1_E4_DESIRED_OPMODE_APV = ptc_matlab_lib.PTC_MBDS_Parameter('Value', ENUM_REAX_OPERATION_MODE_T.POSITION_CTRL_MODE, ...
	'Description', 'Operating mode selection for PropB_REAX_1_E4');

%% PROPB_REAX_1_E4_DESIRED_POSITION_APV
PROPB_REAX_1_E4_DESIRED_POSITION_APV = ptc_matlab_lib.PTC_MBDS_Parameter('Value', 0, ...
	'Description', 'Desired angle position for steering wheel', ...
	'Unit', 'deg', ...
	'Min', -1439.8681640625, ...
	'Max', 1439.8681640625);

%% PROPB_REAX_1_E4_DES_POS_SIG_SRC_APV
PROPB_REAX_1_E4_DES_POS_SIG_SRC_APV = ptc_matlab_lib.PTC_MBDS_Parameter('Value', ENUM_STEERING_POS_SIGNAL_SOURCE_T.ESTIMATION, ...
	'Description', 'Signal source for desired steering angle position in PropB_REAX_1');

%% TSC1_XXE_E4_CONTROL_PURPOSE_APV
TSC1_XXE_E4_CONTROL_PURPOSE_APV = ptc_matlab_lib.PTC_MBDS_Parameter('Value', ENUM_TSC1_CONTROL_PURPOSE_T.P1_ACCELERATOR_OPERATOR, ...
	'Description', 'Control purpose selection for TSC1_XXE_E4');

%% TSC1_XXE_E4_ENGINE_OV_CTRL_MODE_APV
TSC1_XXE_E4_ENGINE_OV_CTRL_MODE_APV = ptc_matlab_lib.PTC_MBDS_Parameter('Value', ENUM_TSC1_ENG_OV_CTRL_MODE_T.TORQUE_CONTROL, ...
	'Description', 'Engine override control mode selection for TSC1_XXE_E4');

%% LONG_SPEED_SRC_SELECTOR_APV
LONG_SPEED_SRC_SELECTOR_APV = ptc_matlab_lib.PTC_MBDS_Parameter('Value', ENUM_LONG_SPEED_DEMAND_SOURCE_T.GPS_PATH,...
    'Description', 'Selector for longitudnal speed control source');
