%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% Autogenerated by export_data_dictionary.m
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

%% DIAG_CAN1_Count_Ack_Errors
DIAG_CAN1_Count_Ack_Errors = ptc_matlab_lib.PTC_MBDS_Signal();

%% DIAG_CAN1_Count_Bit0_Errors
DIAG_CAN1_Count_Bit0_Errors = ptc_matlab_lib.PTC_MBDS_Signal();

%% DIAG_CAN1_Count_Bit1_Errors
DIAG_CAN1_Count_Bit1_Errors = ptc_matlab_lib.PTC_MBDS_Signal();

%% DIAG_CAN1_Count_CRC_Errors
DIAG_CAN1_Count_CRC_Errors = ptc_matlab_lib.PTC_MBDS_Signal();

%% DIAG_CAN1_Count_Format_Errors
DIAG_CAN1_Count_Format_Errors = ptc_matlab_lib.PTC_MBDS_Signal();

%% DIAG_CAN1_Count_RX_Lost
DIAG_CAN1_Count_RX_Lost = ptc_matlab_lib.PTC_MBDS_Signal();

%% DIAG_CAN1_Count_RX_OK
DIAG_CAN1_Count_RX_OK = ptc_matlab_lib.PTC_MBDS_Signal();

%% DIAG_CAN1_Count_Stuff_Errors
DIAG_CAN1_Count_Stuff_Errors = ptc_matlab_lib.PTC_MBDS_Signal();

%% DIAG_CAN1_Count_TX_OK
DIAG_CAN1_Count_TX_OK = ptc_matlab_lib.PTC_MBDS_Signal();

%% DIAG_CAN1_Status
DIAG_CAN1_Status = ptc_matlab_lib.PTC_MBDS_Signal();

%% DIAG_CAN2_Count_Ack_Errors
DIAG_CAN2_Count_Ack_Errors = ptc_matlab_lib.PTC_MBDS_Signal();

%% DIAG_CAN2_Count_Bit0_Errors
DIAG_CAN2_Count_Bit0_Errors = ptc_matlab_lib.PTC_MBDS_Signal();

%% DIAG_CAN2_Count_Bit1_Errors
DIAG_CAN2_Count_Bit1_Errors = ptc_matlab_lib.PTC_MBDS_Signal();

%% DIAG_CAN2_Count_CRC_Errors
DIAG_CAN2_Count_CRC_Errors = ptc_matlab_lib.PTC_MBDS_Signal();

%% DIAG_CAN2_Count_Format_Errors
DIAG_CAN2_Count_Format_Errors = ptc_matlab_lib.PTC_MBDS_Signal();

%% DIAG_CAN2_Count_RX_Lost
DIAG_CAN2_Count_RX_Lost = ptc_matlab_lib.PTC_MBDS_Signal();

%% DIAG_CAN2_Count_RX_OK
DIAG_CAN2_Count_RX_OK = ptc_matlab_lib.PTC_MBDS_Signal();

%% DIAG_CAN2_Count_Stuff_Errors
DIAG_CAN2_Count_Stuff_Errors = ptc_matlab_lib.PTC_MBDS_Signal();

%% DIAG_CAN2_Count_TX_OK
DIAG_CAN2_Count_TX_OK = ptc_matlab_lib.PTC_MBDS_Signal();

%% DIAG_CAN2_Status
DIAG_CAN2_Status = ptc_matlab_lib.PTC_MBDS_Signal();

%% DIAG_CAN3_Count_Ack_Errors
DIAG_CAN3_Count_Ack_Errors = ptc_matlab_lib.PTC_MBDS_Signal();

%% DIAG_CAN3_Count_Bit0_Errors
DIAG_CAN3_Count_Bit0_Errors = ptc_matlab_lib.PTC_MBDS_Signal();

%% DIAG_CAN3_Count_Bit1_Errors
DIAG_CAN3_Count_Bit1_Errors = ptc_matlab_lib.PTC_MBDS_Signal();

%% DIAG_CAN3_Count_CRC_Errors
DIAG_CAN3_Count_CRC_Errors = ptc_matlab_lib.PTC_MBDS_Signal();

%% DIAG_CAN3_Count_Format_Errors
DIAG_CAN3_Count_Format_Errors = ptc_matlab_lib.PTC_MBDS_Signal();

%% DIAG_CAN3_Count_RX_Lost
DIAG_CAN3_Count_RX_Lost = ptc_matlab_lib.PTC_MBDS_Signal();

%% DIAG_CAN3_Count_RX_OK
DIAG_CAN3_Count_RX_OK = ptc_matlab_lib.PTC_MBDS_Signal();

%% DIAG_CAN3_Count_Stuff_Errors
DIAG_CAN3_Count_Stuff_Errors = ptc_matlab_lib.PTC_MBDS_Signal();

%% DIAG_CAN3_Count_TX_OK
DIAG_CAN3_Count_TX_OK = ptc_matlab_lib.PTC_MBDS_Signal();

%% DIAG_CAN3_Status
DIAG_CAN3_Status = ptc_matlab_lib.PTC_MBDS_Signal();

%% DIAG_CAN4_Count_Ack_Errors
DIAG_CAN4_Count_Ack_Errors = ptc_matlab_lib.PTC_MBDS_Signal();

%% DIAG_CAN4_Count_Bit0_Errors
DIAG_CAN4_Count_Bit0_Errors = ptc_matlab_lib.PTC_MBDS_Signal();

%% DIAG_CAN4_Count_Bit1_Errors
DIAG_CAN4_Count_Bit1_Errors = ptc_matlab_lib.PTC_MBDS_Signal();

%% DIAG_CAN4_Count_CRC_Errors
DIAG_CAN4_Count_CRC_Errors = ptc_matlab_lib.PTC_MBDS_Signal();

%% DIAG_CAN4_Count_Format_Errors
DIAG_CAN4_Count_Format_Errors = ptc_matlab_lib.PTC_MBDS_Signal();

%% DIAG_CAN4_Count_RX_Lost
DIAG_CAN4_Count_RX_Lost = ptc_matlab_lib.PTC_MBDS_Signal();

%% DIAG_CAN4_Count_RX_OK
DIAG_CAN4_Count_RX_OK = ptc_matlab_lib.PTC_MBDS_Signal();

%% DIAG_CAN4_Count_Stuff_Errors
DIAG_CAN4_Count_Stuff_Errors = ptc_matlab_lib.PTC_MBDS_Signal();

%% DIAG_CAN4_Count_TX_OK
DIAG_CAN4_Count_TX_OK = ptc_matlab_lib.PTC_MBDS_Signal();

%% DIAG_CAN4_Status
DIAG_CAN4_Status = ptc_matlab_lib.PTC_MBDS_Signal();

%% DIAG_CAN5_Count_Ack_Errors
DIAG_CAN5_Count_Ack_Errors = ptc_matlab_lib.PTC_MBDS_Signal();

%% DIAG_CAN5_Count_Bit0_Errors
DIAG_CAN5_Count_Bit0_Errors = ptc_matlab_lib.PTC_MBDS_Signal();

%% DIAG_CAN5_Count_Bit1_Errors
DIAG_CAN5_Count_Bit1_Errors = ptc_matlab_lib.PTC_MBDS_Signal();

%% DIAG_CAN5_Count_CRC_Errors
DIAG_CAN5_Count_CRC_Errors = ptc_matlab_lib.PTC_MBDS_Signal();

%% DIAG_CAN5_Count_Format_Errors
DIAG_CAN5_Count_Format_Errors = ptc_matlab_lib.PTC_MBDS_Signal();

%% DIAG_CAN5_Count_RX_Lost
DIAG_CAN5_Count_RX_Lost = ptc_matlab_lib.PTC_MBDS_Signal();

%% DIAG_CAN5_Count_RX_OK
DIAG_CAN5_Count_RX_OK = ptc_matlab_lib.PTC_MBDS_Signal();

%% DIAG_CAN5_Count_Stuff_Errors
DIAG_CAN5_Count_Stuff_Errors = ptc_matlab_lib.PTC_MBDS_Signal();

%% DIAG_CAN5_Count_TX_OK
DIAG_CAN5_Count_TX_OK = ptc_matlab_lib.PTC_MBDS_Signal();

%% DIAG_CAN5_Status
DIAG_CAN5_Status = ptc_matlab_lib.PTC_MBDS_Signal();

%% DIAG_CAN6_Count_Ack_Errors
DIAG_CAN6_Count_Ack_Errors = ptc_matlab_lib.PTC_MBDS_Signal();

%% DIAG_CAN6_Count_Bit0_Errors
DIAG_CAN6_Count_Bit0_Errors = ptc_matlab_lib.PTC_MBDS_Signal();

%% DIAG_CAN6_Count_Bit1_Errors
DIAG_CAN6_Count_Bit1_Errors = ptc_matlab_lib.PTC_MBDS_Signal();

%% DIAG_CAN6_Count_CRC_Errors
DIAG_CAN6_Count_CRC_Errors = ptc_matlab_lib.PTC_MBDS_Signal();

%% DIAG_CAN6_Count_Format_Errors
DIAG_CAN6_Count_Format_Errors = ptc_matlab_lib.PTC_MBDS_Signal();

%% DIAG_CAN6_Count_RX_Lost
DIAG_CAN6_Count_RX_Lost = ptc_matlab_lib.PTC_MBDS_Signal();

%% DIAG_CAN6_Count_RX_OK
DIAG_CAN6_Count_RX_OK = ptc_matlab_lib.PTC_MBDS_Signal();

%% DIAG_CAN6_Count_Stuff_Errors
DIAG_CAN6_Count_Stuff_Errors = ptc_matlab_lib.PTC_MBDS_Signal();

%% DIAG_CAN6_Count_TX_OK
DIAG_CAN6_Count_TX_OK = ptc_matlab_lib.PTC_MBDS_Signal();

%% DIAG_CAN6_Status
DIAG_CAN6_Status = ptc_matlab_lib.PTC_MBDS_Signal();

%% GLB_Absolute_Timestamp
GLB_Absolute_Timestamp = ptc_matlab_lib.PTC_MBDS_Signal('Description', 'Global timestamp', ...
	'Unit', 's');

%% CurrentAzimuth_rad
CurrentAzimuth_rad = ptc_matlab_lib.PTC_MBDS_Signal('Description', 'Current Azimuth', ...
	'Unit', 'rad');

%% TargetAzimuth_rad
TargetAzimuth_rad = ptc_matlab_lib.PTC_MBDS_Signal('Description', 'Target Azimuth', ...
	'Unit', 'rad');

%% CurrentVelocity_kph
CurrentVelocity_kph = ptc_matlab_lib.PTC_MBDS_Signal('Description', 'Current Velocity', ...
	'Unit', 'kph');

%% TargetVelocity_kph
TargetVelocity_kph = ptc_matlab_lib.PTC_MBDS_Signal('Description', 'Target Velocity', ...
	'Unit', 'kph');
