%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% Autogenerated by export_data_dictionary.m
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

%% AcceleratorPedalPosOut
AcceleratorPedalPosOut = ptc_matlab_lib.PTC_MBDS_Signal();

%% DriverDemPercentTrq
DriverDemPercentTrq = ptc_matlab_lib.PTC_MBDS_Signal();

%% EngSpeedRPM
EngSpeedRPM = ptc_matlab_lib.PTC_MBDS_Signal();

%% EngTrqDemand
EngTrqDemand = ptc_matlab_lib.PTC_MBDS_Signal();

%% FrontAxleSpd
FrontAxleSpd = ptc_matlab_lib.PTC_MBDS_Signal();

%% GearNumberActual
GearNumberActual = ptc_matlab_lib.PTC_MBDS_Signal();

%% GearNumberCommand
GearNumberCommand = ptc_matlab_lib.PTC_MBDS_Signal();

%% MainClutch
MainClutch = ptc_matlab_lib.PTC_MBDS_Signal();

%% OCM
OCM = ptc_matlab_lib.PTC_MBDS_Signal();

%% SPN190_EngineSpeed
SPN190_EngineSpeed = ptc_matlab_lib.PTC_MBDS_Signal();

%% SPN4976_PitchAngleExtendedRange
SPN4976_PitchAngleExtendedRange = ptc_matlab_lib.PTC_MBDS_Signal();

%% SPN513_ActualEngPercTorque
SPN513_ActualEngPercTorque = ptc_matlab_lib.PTC_MBDS_Signal();

%% SPN514_NominalFrictionPercTorque
SPN514_NominalFrictionPercTorque = ptc_matlab_lib.PTC_MBDS_Signal();

%% SPN520_ActualRetarderPercentTorque
SPN520_ActualRetarderPercentTorque = ptc_matlab_lib.PTC_MBDS_Signal();

%% SPN523_TransCurrentGear
SPN523_TransCurrentGear = ptc_matlab_lib.PTC_MBDS_Signal();

%% SPN526_TransActualGearRatio
SPN526_TransActualGearRatio = ptc_matlab_lib.PTC_MBDS_Signal();

%% SPN527_CruiseControlState
SPN527_CruiseControlState = ptc_matlab_lib.PTC_MBDS_Signal();

%% SPN560_TransDrivelineEngaged
SPN560_TransDrivelineEngaged = ptc_matlab_lib.PTC_MBDS_Signal();

%% SPN7319_CruiseControlSpeed
SPN7319_CruiseControlSpeed = ptc_matlab_lib.PTC_MBDS_Signal('Unit', 'km/h');

%% SPN84_WheelBasedVehicleSpeed
SPN84_WheelBasedVehicleSpeed = ptc_matlab_lib.PTC_MBDS_Signal('Unit', 'km/h');

%% SPN86_CruiseControlSetSpeed
SPN86_CruiseControlSetSpeed = ptc_matlab_lib.PTC_MBDS_Signal('Unit', 'km/h');

%% SPN917_TotalVehicleDistanceHiResolution
SPN917_TotalVehicleDistanceHiResolution = ptc_matlab_lib.PTC_MBDS_Signal();

%% SPN91_AccelPedalPosition1
SPN91_AccelPedalPosition1 = ptc_matlab_lib.PTC_MBDS_Signal();

%% ShiftControlState
ShiftControlState = ptc_matlab_lib.PTC_MBDS_Signal();

%% TransStateLock
TransStateLock = ptc_matlab_lib.PTC_MBDS_Signal();

%% TrqReq
TrqReq = ptc_matlab_lib.PTC_MBDS_Signal();

%% ActualVehicleDistance
ActualVehicleDistance = ptc_matlab_lib.PTC_MBDS_Signal();

%% RefVehSpeed
RefVehSpeed = ptc_matlab_lib.PTC_MBDS_Signal();

%% RefFuelRate
RefFuelRate = ptc_matlab_lib.PTC_MBDS_Signal();

%% RefEngSpeed
RefEngSpeed = ptc_matlab_lib.PTC_MBDS_Signal();

%% RefNetTrq
RefNetTrq = ptc_matlab_lib.PTC_MBDS_Signal();

%% PitchAngle
PitchAngle = ptc_matlab_lib.PTC_MBDS_Signal();

%% L4OperatorEnable
L4OperatorEnable = ptc_matlab_lib.PTC_MBDS_Signal();

%% CCSetSpeed
CCSetSpeed = ptc_matlab_lib.PTC_MBDS_Signal();

%% BrkDrv
BrkDrv = ptc_matlab_lib.PTC_MBDS_Signal();

%% OperatorEnable
OperatorEnable = ptc_matlab_lib.PTC_MBDS_Signal();

%% PedDrv
PedDrv = ptc_matlab_lib.PTC_MBDS_Signal();

%% Lateral_Control_Heading_Error [Used by KW]
Lateral_Control_Heading_Error = ptc_matlab_lib.PTC_MBDS_Signal('Description', 'Lateral Control Heading Error', ...
    'Unit', 'rad');

%% Steering_PID_Output [Used by KW]
Steering_PID_Output = ptc_matlab_lib.PTC_MBDS_Signal('Description', 'Steering Controller PID Output', ...
    'Unit', 'rad');

%% SteerCommand [Used by KW]
SteerCommand = ptc_matlab_lib.PTC_MBDS_Signal('Description', 'Steer Command Output', ...
    'Unit', 'rad');

%% SteerCommandDeg [Used by KW]
SteerCommandDeg = ptc_matlab_lib.PTC_MBDS_Signal('Description', 'Steer Command Output Degrees [Sign inverted]', ...
    'Unit', 'deg');

%% DesiredSteeringAngle
DesiredSteeringAngle = ptc_matlab_lib.PTC_MBDS_Signal('Description', 'Desired Steering Wheel Angle Output', ...
    'Unit', 'deg');
