function varargout = svnsync(varargin)
%SVNSYNC: This function will synchronize the specified directory with svn.
%This operation includes removing unversioned files, so be careful while
%using it.

import('ptc_matlab_lib.*');

pairs = {'SVNROOT', pwd, ...
    'ShouldEcho', false, ...
    'ShouldForceConsistency', true, ...
    'SVNUserName', username(), ...    
    'SVNPassword', ''};
ARGS = parseargs(varargin, pairs);

if isempty(ARGS.SVNUserName) || isempty(ARGS.SVNPassword)
    [ARGS.SVNUserName, ARGS.SVNPassword] = ptc_matlab_lib.uilogin('DefaultUser', ptc_matlab_lib.username, 'FigureParams', {'WindowStyle', 'modal'});
end
if isequal(ARGS.SVNUserName, 0) || isequal(ARGS.SVNPassword, 0)
    %Cancel was pressed
    varargout{1} = false;
    return;
end

varargout{1} = svn_consistency_check('SVNROOT', ARGS.SVNROOT, ...
    'ShowDialog', false, ...
    'ShouldUpdate', true, ...
    'ShouldForceConsistency', ARGS.ShouldForceConsistency, ...
    'ShouldEcho', ARGS.ShouldEcho, ...
    'SVNUserName', ARGS.SVNUserName, ...
    'SVNPassword', ARGS.SVNPassword);

end