function varargout = uiedit_MATLABExpression(varargin)

import('ptc_matlab_lib.*');

if length(varargin) >= 2 && isscalar(varargin{1}) && ishghandle(varargin{1})
    %This is a GUI Callback
    SRC_HANDLE = varargin{1}; %#ok<NASGU>
    EVENT_DATA = varargin{2}; %#ok<NASGU>
    assert(length(varargin) >= 2);
    varargin = varargin(3:end);
else
    SRC_HANDLE = []; %#ok<NASGU>
    EVENT_DATA = struct([]); %#ok<NASGU>
end

pairs = {'action', 'init'};
parseargs(varargin, pairs);

persistent DELETE_THESE_HANDLES;
persistent FIGURE_HANDLE;
persistent MATLAB_EXPRESSION_RETURN;

switch action
    %% CASE init
    case 'init'
        pairs = {'InitExpression', '', ...
            'IdentifierList', {''}, ...
            'OperatorList', {'(', ')', '&', '&&', '|', '||', '~', 'xor(', ','}, ...
            'WindowStyle', 'modal'};
        parseargs(varargin, pairs);
        
        pairs = {['fig_' mfilename '_position'],      [0.30893     0.23619      0.3875     0.52476], ...
            'uipanelOperatorFunctionList_position',      [0.68817     0.17967     0.23195     0.45554], ...
            'uipanelIdentifierList_position',     [0.075269     0.17967     0.61598     0.45554], ...
            'btnCancel_position',      [0.50077    0.045372     0.15515    0.092559], ...
            'btnOK_position',      [0.34716    0.045372     0.15515    0.092559], ...
            'btnClear_position',      [0.76651     0.69873     0.15515     0.14156], ...
            'textMATLABExpressionBuilder_position',     [0.075269     0.88203     0.84639    0.043557], ...
            'editExpression_position',     [0.075269     0.69873     0.69278     0.14156], ...
            'listboxOperatorFunctionList_position',      [0.14966    0.094017     0.72789     0.85897], ...
            'btnReset_position',      [0.67254     0.80342     0.25441     0.12821], ...
            'btnFilter_position',      [0.42065     0.80342     0.25441     0.12821], ...
            'editRegularExpressionFilter_position',     [0.075567     0.80342     0.34761     0.12821], ...
            'listboxIdentifierList_position',     [0.075567     0.11966     0.85642     0.67949]};
        parseargs(pairs);
        
        if isfigure(FIGURE_HANDLE)
            figure(FIGURE_HANDLE);
            return;
        end
        
        FIGURE_HANDLE = dialog('MenuBar', 'none', ...
            'Name', mfilename, ...
            'Resize', 'off', ...
            'Units', 'normalized', ...
            'WindowStyle', WindowStyle, ...
            'CreateFcn', {@movegui, 'center'}, ...
            'Position', eval(['fig_' mfilename '_position']), ...
            'DeleteFcn', {str2func(thisfuncname), 'action', 'close'}, ...
            'CloseRequestFcn', {str2func(thisfuncname), 'action', 'btnCancelCallback'});
        
        DELETE_THESE_HANDLES = FIGURE_HANDLE;
        
        %textMATLABExpressionBuilder
        uicontrol('Parent', FIGURE_HANDLE, ...
            'Units', 'normalized', ...
            'Tag', 'textMATLABExpressionBuilder', ...
            'Position', textMATLABExpressionBuilder_position, ...
            'Style', 'text', ...
            'BackgroundColor', 'yellow', ...
            'String', 'MATLAB Expression Builder', ...
            'FontWeight', 'bold', ...
            'FontSize', 13.0);
        
        %editExpression
        uicontrol('Parent', FIGURE_HANDLE, ...
            'Units', 'normalized', ...
            'Tag', 'editExpression', ...
            'Position', editExpression_position, ...
            'Style', 'edit', ...
            'BackgroundColor', 'white', ...
            'String', InitExpression, ...
            'FontName', editfont, ...
            'FontSize', 10.0, ...
            'Max', 9999999, ...
            'HorizontalAlignment', 'left');
        
        %btnClear
        uicontrol('Parent', FIGURE_HANDLE, ...
            'Units', 'normalized', ...
            'Tag', 'btnClear', ...
            'Position', btnClear_position, ...
            'Style', 'pushbutton', ...
            'String', 'CLEAR', ...
            'Callback', {str2func(thisfuncname), 'action', 'btnClearCallback'});
        
        %uipanelIdentifierList
        hndl_uipanelIdentifierList = uipanel('Parent', FIGURE_HANDLE, ...
            'Units', 'normalized', ...
            'Tag', 'uipanelIdentifierList', ...
            'Position', uipanelIdentifierList_position, ...
            'Title', 'Identifier List');
        
        %uipanelOperatorFunctionList
        hndl_uipanelOperatorFunctionList = uipanel('Parent', FIGURE_HANDLE, ...
            'Units', 'normalized', ...
            'Tag', 'uipanelOperatorFunctionList', ...
            'Position', uipanelOperatorFunctionList_position, ...
            'Title', 'Operator/Function List');
        
        %editRegularExpressionFilter
        uicontrol('Parent', hndl_uipanelIdentifierList, ...
            'Units', 'normalized', ...
            'Tag', 'editRegularExpressionFilter', ...
            'Position', editRegularExpressionFilter_position, ...
            'Style', 'edit', ...
            'BackgroundColor', 'white', ...
            'FontSize', 10.0, ...
            'FontName', editfont);
        
        %btnFilter
        uicontrol('Parent', hndl_uipanelIdentifierList, ...
            'Units', 'normalized', ...
            'Tag', 'btnFilter', ...
            'Position', btnFilter_position, ...
            'Style', 'pushbutton', ...
            'String', 'FILTER', ...
            'Callback', {str2func(thisfuncname), 'action', 'btnFilterCallback'});
        
        %btnReset
        uicontrol('Parent', hndl_uipanelIdentifierList, ...
            'Units', 'normalized', ...
            'Tag', 'btnReset', ...
            'Position', btnReset_position, ...
            'Style', 'pushbutton', ...
            'String', 'RESET', ...
            'Callback', {str2func(thisfuncname), 'action', 'btnResetCallback'});
        
        %listboxIdentifierList
        h = uicontrol('Parent', hndl_uipanelIdentifierList, ...
            'Units', 'normalized', ...
            'Tag', 'listboxIdentifierList', ...
            'Position', listboxIdentifierList_position, ...
            'Style', 'listbox', ...
            'BackgroundColor', 'white', ...
            'String', IdentifierList, ...
            'FontName', editfont, ...
            'FontSize', 10.0, ...
            'Callback', {str2func(thisfuncname), 'action', 'listboxIdentifierListCallback'});
        setappdata(h, 'CompleteIdentifierList', IdentifierList);
        
        %listboxOperatorFunctionList
        uicontrol('Parent', hndl_uipanelOperatorFunctionList, ...
            'Units', 'normalized', ...
            'Tag', 'listboxOperatorFunctionList', ...
            'Position', listboxOperatorFunctionList_position, ...
            'Style', 'listbox', ...
            'BackgroundColor', 'white', ...
            'String', OperatorList, ...
            'FontName', editfont, ...
            'FontSize', 10.0, ...
            'Callback', {str2func(thisfuncname), 'action', 'listboxOperatorFunctionListCallback'});
        
        %btnOK
        uicontrol('Parent', FIGURE_HANDLE, ...
            'Units', 'normalized', ...
            'Tag', 'btnOK', ...
            'Position', btnOK_position, ...
            'Style', 'pushbutton', ...
            'String', 'OK', ...
            'Callback', {str2func(thisfuncname), 'action', 'btnOKCallback'});
        
        %btnCancel
        uicontrol('Parent', FIGURE_HANDLE, ...
            'Units', 'normalized', ...
            'Tag', 'btnCancel', ...
            'Position', btnCancel_position, ...
            'Style', 'pushbutton', ...
            'String', 'CANCEL', ...
            'Callback', {str2func(thisfuncname), 'action', 'btnCancelCallback'});
        
        waitfor(FIGURE_HANDLE);
        
        varargout{1} = MATLAB_EXPRESSION_RETURN;
        clear(mfilename);
        
        %% CASE listboxOperatorFunctionListCallback
    case 'listboxOperatorFunctionListCallback'
        handles = guihandles(FIGURE_HANDLE);
        if strcmp(get(FIGURE_HANDLE, 'SelectionType'), 'open')
            initstr = strtrim(strimplode(strtrim(cellstr(get(handles.editExpression, 'String'))), ' '));
            thisValue = get(handles.listboxOperatorFunctionList, 'Value');
            thisList = get(handles.listboxOperatorFunctionList, 'String');
            finalstr = strtrim([initstr ' ' thisList{thisValue}]);
            set(handles.editExpression, 'String', finalstr);
        end
        
        %% CASE listboxIdentifierListCallback
    case 'listboxIdentifierListCallback'
        handles = guihandles(FIGURE_HANDLE);
        if strcmp(get(FIGURE_HANDLE, 'SelectionType'), 'open')
            initstr = strtrim(strimplode(strtrim(cellstr(get(handles.editExpression, 'String'))), ' '));
            
            thisList = get(handles.listboxIdentifierList, 'String');
            thisValue = get(handles.listboxIdentifierList, 'Value');
            
            finalstr = strtrim([initstr ' ' thisList{thisValue}]);
            set(handles.editExpression, 'String', finalstr);
        end
        
        %% CASE btnFilterCallback
    case 'btnFilterCallback'
        handles = guihandles(FIGURE_HANDLE);
        pattern = strtrim(char(get(handles.editRegularExpressionFilter, 'String')));
        
        if ~isempty(pattern)
            oldstr = get(handles.listboxIdentifierList, 'String');
            try
                result = regexpi(oldstr, pattern);
                newstr = oldstr(~cellfun(@isempty, result));
                set(handles.listboxIdentifierList, 'Value', 1);
                if isempty(newstr)
                    newstr = {''};
                end
                set(handles.listboxIdentifierList, 'String', newstr);
            end
        end
        
        %% CASE btnResetCallback
    case 'btnResetCallback'
        handles = guihandles(FIGURE_HANDLE);
        set(handles.editRegularExpressionFilter, 'String', '');
        newstr = getappdata(handles.listboxIdentifierList, 'CompleteIdentifierList');
        set(handles.listboxIdentifierList, 'String', newstr);
        
        %% CASE btnClearCallback
    case 'btnClearCallback'
        handles = guihandles(FIGURE_HANDLE);
        set(handles.editExpression, 'String', '');
        
        %% CASE btnCancelCallback
    case 'btnCancelCallback'
        MATLAB_EXPRESSION_RETURN = '';
        feval(thisfuncname, 'action', 'close');
        
        %% CASE btnOKCallback
    case 'btnOKCallback'
        handles = guihandles(FIGURE_HANDLE);
        thisstr = strtrim(cellstr(get(handles.editExpression, 'String')));
        thisstr = strimplode(thisstr, ' ');
        thisstr = regexprep(thisstr, '\s+', ' ');
        
        if ~isempty(strtrim(thisstr))
            MATLAB_EXPRESSION_RETURN = thisstr;
            feval(thisfuncname, 'action', 'close');
        else
            waitfor(errordlg('The expression field cannot be left blank', 'ERROR', 'modal'));
        end
        
        %% CASE close
    case 'close'
        for ctr = 1:numel(DELETE_THESE_HANDLES)
            try
                delete(DELETE_THESE_HANDLES(ctr));
            end
        end
end

end